### ISSUE TITLE
Check supplied param names against configured list(s) of values

### ISSUE THREAD

**Issue by abacaphiliac** [psecio/canary#1]
Hi @enygma ,

I think it would be useful to check supplied param names against list(s) of values.

In-line example:
```php
$names = ['username', 'password'];

$values = []; // from config

\Psecio\Canary\Instance::build()->if($names, $values)
```

Or via map (in case different values should be restricted per param):
```php
$values = [
  'username' => [], // from config
  'password' => [], // from another config
];

\Psecio\Canary\Instance::build()->if($values)
```

Factoried-instance example, so that instance can be easily shared throughout the application via container:
```php
$instance = \Psecio\Canary\Instance::buildFromConfig([
  'value_map' => [
    'username' => [], // from config
    'password' => [], // from another config],
  ]
);

$instance->isValid($_GET, $_POST);
```

In the last example, I've added an isValid method, which is variadic and checks multiple arrays. If no params are supplied, we could check $_GET and $_POST by default (per your examples), but it would probably be better to grab those values from a ServerRequest instance.

In the suggested `buildFromConfig` method, we could accept explicit maps (as shown), and/or fall-back to default lists of known-bad values, e.g. rainbow-tree kind of lists.

What do you think?

Source: https://twitter.com/abacaphiliac/status/964536217667686400

**Comment by enygma** [comment]
@abacaphiliac So I added support for passing in multiple options as an array like this:

```php
<?php
$criteria = [
    'test' => 'foo',
    'bar' => 'baz
];
\Psecio\Canary\Instance::build()->if($criteria)->execute();

?>
```

Does this satisfy your need?

**Comment by abacaphiliac** [comment]
@enygma cool. in your example, `test` and `bar` are params? with `foo` and `baz` respective values? is it possible to specify multiple values per param name?

**Comment by enygma** [comment]
@abacaphiliac Correct, those are the param names and values. Currently there's not a way to have multiple values but it wouldn't be too difficult to add, really - just an `if` check on the type of the value.

**Comment by abacaphiliac** [comment]
@enygma mind if i take a crack at adding the test and change?

**Comment by enygma** [comment]
@abacaphiliac Go for it - PRs are always appreciated!

**Comment by abacaphiliac** [comment]
i think this is good. thanks for letting me participate : )
